markdown: kramdown
highlighter: pygments
highlight: true
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: daiwk
author: "daiwk"
email: daiwk#foxmail.com
name: "daiwk-github博客"
url: http://daiwk.github.io
domain: daiwk.github.io
all_categories: [
["nlp", "nlp","/posts/nlp.html"], 
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: China/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate




kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"